name: cross-platform build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:            
            - os: ubuntu-latest
              arch: x64-sse4-popcnt
              simd: ENABLE_SIMD_SSE4_2
              arch_exclusive: OFF
              bmi2: OFF

            - os: ubuntu-latest
              arch: x64-avx2
              simd: ENABLE_SIMD_AVX2
              arch_exclusive: OFF
              bmi2: ON

            - os: windows-latest
              arch: x64-sse4-popcnt
              simd: ENABLE_SIMD_SSE4_2
              arch_exclusive: OFF
              bmi2: OFF

            - os: windows-latest
              arch: x64-avx2
              simd: ENABLE_SIMD_AVX2
              arch_exclusive: OFF
              bmi2: ON

            - os: ubuntu-24.04-arm
              arch: arm64
              simd: ARCHITECTURE_ARM
              arch_exclusive: OFF
              bmi2: OFF


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install CMake on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: >
        cmake -B ${{ github.workspace }}/build 
        -DCMAKE_BUILD_TYPE=Release 
        -D${{ matrix.simd }}=ON
        -DARCHITECTURE_EXCLUSIVE=${{ matrix.arch_exclusive }}
        -DEXTENSION_BMI2=${{ matrix.bmi2 }}

    - name: Build Project
      run: cmake --build ${{ github.workspace }}/build --config Release --parallel

    - name: Smoke Test on Linux
      if: runner.os == 'Linux'
      working-directory: ${{ github.workspace }}
      run: ./bin/Leaf/Release/Leaf bench

    - name: Smoke Test on Windows
      if: runner.os == 'Windows'
      working-directory: ${{ github.workspace }}
      run: .\bin\Leaf\Release\Release\Leaf.exe bench
